# Generated by Django 5.2.7 on 2025-12-06 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Kullanıcı Adı')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Ad Soyad')),
                ('role', models.CharField(choices=[('individual', 'Birey'), ('support_required_individual', 'Destek Gereksinimli Birey'), ('responsible_person', 'Sorumlu Kişi')], default='individual', max_length=30, verbose_name='Rol')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profil Resmi')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'db_table': 'users_user',
            },
        ),
        migrations.CreateModel(
            name='SupportRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('parent', 'Ebeveyn'), ('guardian', 'Vasi'), ('caregiver', 'Bakıcı'), ('therapist', 'Terapist'), ('teacher', 'Öğretmen'), ('other', 'Diğer')], default='parent', max_length=50, verbose_name='İlişki Türü')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('individual', models.ForeignKey(limit_choices_to={'role': 'support_required_individual'}, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_persons', to=settings.AUTH_USER_MODEL, verbose_name='Destek Gereksinimli Birey')),
                ('responsible_person', models.ForeignKey(limit_choices_to={'role': 'responsible_person'}, on_delete=django.db.models.deletion.CASCADE, related_name='supported_individuals', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu Kişi')),
            ],
            options={
                'verbose_name': 'Destek İlişkisi',
                'verbose_name_plural': 'Destek İlişkileri',
                'db_table': 'users_support_relationship',
                'ordering': ['-created_at'],
                'unique_together': {('responsible_person', 'individual')},
            },
        ),
    ]
