# Generated by Django 5.2.7 on 2025-12-04 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('task_type', models.CharField(choices=[('single', 'Tekli Görev'), ('routine', 'Rutin Görev')], default='single', max_length=20, verbose_name='Görev Tipi')),
                ('category', models.CharField(choices=[('hygiene', 'Hijyen'), ('education', 'Eğitim'), ('social', 'Sosyal'), ('health', 'Sağlık'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Kategori')),
                ('scheduled_date', models.DateField(db_column='date', verbose_name='Tarih')),
                ('start_time', models.TimeField(verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Bitiş Saati')),
                ('estimated_duration', models.IntegerField(blank=True, null=True, verbose_name='Tahmini Süre (dakika)')),
                ('lottie_animation', models.CharField(blank=True, max_length=200, verbose_name='Lottie Animasyon')),
                ('lottie_url', models.URLField(blank=True, verbose_name='Lottie URL')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='tasks/videos/', verbose_name='Video Dosyası')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tasks/images/', verbose_name='Görsel')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='tasks/audio/', verbose_name='Ses Dosyası')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], default='medium', max_length=20, verbose_name='Öncelik')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Kolay'), ('medium', 'Orta'), ('hard', 'Zor')], default='medium', max_length=20, verbose_name='Zorluk Seviyesi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('completed', models.BooleanField(default=False, verbose_name='Tamamlandı mı?')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('assigned_to', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kullanıcı')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
                'db_table': 'tasks_task',
                'ordering': ['-scheduled_date', '-start_time'],
            },
        ),
    ]
