# Generated by Django 5.2.7 on 2025-12-26 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_assigned_to_alter_task_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('title', 'scheduled_date', 'start_time', 'end_time', 'assigned_to')},
        ),
    ]
